# Generated by Django 4.1 on 2022-09-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_familiares_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipocategoria', models.IntegerField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Posiciontrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=80)),
                ('tiemposector', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajocompas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familiares',
        ),
    ]
