# Generated by Django 4.1 on 2022-10-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_categoria_tipocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletasPadel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('material', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=80)),
                ('forma', models.CharField(max_length=80)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Posiciontrabajo',
            new_name='Pelotas',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Trabajocompas',
        ),
        migrations.RenameField(
            model_name='pelotas',
            old_name='sector',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='pelotas',
            old_name='tiemposector',
            new_name='precio',
        ),
    ]
