# Generated by Django 4.1 on 2022-10-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletaspadel',
            name='imagen',
            field=models.ImageField(null=True, upload_to='paletas'),
        ),
        migrations.AddField(
            model_name='pelotas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pelotas'),
        ),
    ]
